name: Embold Code Quality Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  embold-scan_fc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven and Run Analysis
        run: |
          for i in 1 2 3; do
            echo "Attempt $i of 3: Running Maven build..."
            if mvn -B clean install -DskipTests -DskipITs -Dmaven.test.skip=true; then
              echo "Maven build succeeded on attempt $i."
              exit 0
            else
              if [ $i -eq 3 ]; then
                echo "Maven build failed after 3 attempts."
                exit 1
              fi
              echo "Maven build failed. Waiting 10 seconds before retrying..."
              sleep 10
            fi
          done

      - name: Download and Extract Scanner
        run: |
          curl ${{ vars.EMBOLD_SCANNER_URL }} -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz

      - name: Download Repository Configuration
        run: |
          curl --silent --location --request GET \
            "${{ vars.EMBOLD_URL_JAVA }}/api/v1/repositories/fa009b3b6cb03958e4edf6b4fcc88b18/scans/config/download" \
            --header "Authorization: Bearer ${{ secrets.EMBOLD_TOKEN_JAVA }}" \
            -o repository-configuration.json

      - name: Run Embold Scanner
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_SCAN_TOKEN_FC }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
            -u ${{ vars.EMBOLD_URL_JAVA }} \
            -t ${{ secrets.EMBOLD_TOKEN_JAVA }} \
            -r fa009b3b6cb03958e4edf6b4fcc88b18 \
            -b . \
            -d ./embold-data \
            -c ./repository-configuration.json \
            -l ./embold-log \
            -sh ./embold-scanner-home
